# Generated by Django 3.2.12 on 2022-02-11 22:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular bug')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('project', models.CharField(choices=[('cmm', 'CheckMyMetal'), ('o', 'General')], help_text='Project where bug is occuring', max_length=10)),
                ('description', models.TextField(help_text='Enter a brief description of the bug', max_length=1000)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(blank=True, help_text='Institution', max_length=200, null=True)),
                ('location', models.CharField(blank=True, choices=[('us', 'United States'), ('c', 'Canada'), ('m', 'Mexico'), ('a', 'Africa'), ('as', 'Asia'), ('e', 'Europe'), ('o', 'Oceania'), ('sa', 'South America')], default='us', max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('query_type', models.CharField(blank=True, choices=[('b', 'bug'), ('q', 'question'), ('s', 'suggestion'), ('f', 'feedback'), ('l', 'like'), ('d', 'dislike'), ('o', 'other')], default='b', max_length=1, null=True)),
                ('screenshot_or_attachment', models.FileField(blank=True, help_text='Upload screenshot or a problematic data file', null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('nf', 'Not fixed'), ('f', 'Fixed'), ('pf', 'Partially fixed')], default='nf', help_text='Select a status for this bug', max_length=2)),
                ('date_fixed', models.DateField(blank=True, null=True, verbose_name='Fixed')),
            ],
        ),
    ]
