# Generated by Django 3.2.12 on 2022-02-10 16:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.author')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular bug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.CharField(choices=[('cmm', 'CheckMyMetal'), ('o', 'Other')], help_text='Project where bug is occuring', max_length=10)),
                ('description', models.TextField(help_text='Enter a brief description of the bug', max_length=1000)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(blank=True, help_text='Institution', max_length=200, null=True)),
                ('location', models.CharField(blank=True, choices=[('us', 'United States'), ('c', 'Canada'), ('m', 'Mexico'), ('a', 'Africa'), ('as', 'Asia'), ('e', 'Europe'), ('o', 'Oceania'), ('sa', 'South America')], default='us', max_length=2, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('query_type', models.CharField(blank=True, choices=[('b', 'bug'), ('q', 'question'), ('s', 'suggestion'), ('f', 'feedback'), ('l', 'like'), ('d', 'dislike'), ('o', 'other')], default='b', max_length=1, null=True)),
                ('screenshot_or_attachment', models.FileField(blank=True, help_text='Upload screenshot or a problematic data file', null=True, upload_to='uploads/')),
                ('status', models.CharField(default='Not fixed', help_text='Select a status for this bug', max_length=20)),
                ('date_fixed', models.DateField(blank=True, null=True, verbose_name='Fixed')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='tracker.Genre'),
        ),
    ]
