# Generated by Django 3.2.12 on 2022-02-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
